config/routes.rb
BackChannelAppFinal::Application.routes.draw do

  get "user/delete_account"

  get "admin/grant_privilege"

  get "admin/revoke_privilege"

  get "admin/delete_user"

  get "search/search_by"

  get "replies/master"

  post "replies/master"

  get "page/search"

  get "page/contact_us"

  get "page/home"

  get "page/login"

  post "page/login"

  get "page/logout"

  resources :replies

  resources :posts

  resources :categories

  root :to => 'page#home'

  match ':controller(/:action(/:id))(.:format)'
  match '*a', :to => 'page#routing_error'

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :replydescription , :post_id

  belongs_to :post
  has_many :replyvotes
  validates :replydescription, :presence => true
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  before_filter :authenticate, :only => [:index,:show,:edit,:new ,:create,:update,:destroy,:voteup,:votedown]

  def authenticate
    if session[:userid].to_s.nil? || session[:userid].to_s.empty?
      redirect_to page_home_path , notice: "You are not authorized to view this page, Please Log in"
    end
  end

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @replies }
    end
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    @reply = Reply.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/new
  # GET /replies/new.json
  def new
    @reply = Reply.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/1/edit
  def edit
    @reply = Reply.find(params[:id])
    @replydescription = @reply.replydescription

  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(params[:reply])

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @reply, notice: 'Reply was successfully created.' }
        format.json { render json: @reply, status: :created, location: @reply }
      else
        format.html { render action: "new" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /replies/1
  # PUT /replies/1.json
  def update
    @reply = Reply.find(params[:id])
    @reply.replydescription = params[:replydescription]
    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        format.html { redirect_to :controller => "replies" , :action => "master", notice: 'Reply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def master



    if params[:commit]
      replydesc = params[:reply]
      post_id = session[:post_id]

      rep = Reply.new
      rep.replydescription = replydesc
      rep.post_id =  post_id
      rep.user_id =  session[:userid]
      rep.save


      #Reply.create(replydescription: replydesc,post_id: post_id )
      @post = Post.find(post_id)
      @replies = @post.replies
      redirect_to "/replies/master/"+post_id
    else
      if !params[:id].nil?
        post_id =   params[:id]
        session[:post_id] = post_id
        @post = Post.find(post_id)
        @replies = @post.replies
        params[:id] = ""
      end
    end

    if(!session[:post_id].to_s.nil?)
      @post = Post.find(session[:post_id].to_s)
      @replies = @post.replies
    end

  end


  def voteup
    replyid = params[:id]
    replyvote = Replyvote.new
    replyvote.replyvotes_id = replyid
    replyvote.studentid = session[:studentid]
    replyvote.save
    redirect_to :controller => "replies", :action => "master"
  end

  def votedown
    replyid = params[:id]
    replyvote = Replyvote.where(["replyvotes_id = :pid and studentid = :sid", { pid: replyid, sid: session[:studentid].to_s }])
    vote_id = replyvote[0].id
    Replyvote.destroy(vote_id)
    redirect_to :controller => "replies", :action => "master"
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to :controller => "replies" , :action => "master" }
      format.json { head :no_content }
    end
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
    <% if @reply.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

          <ul>
            <% @reply.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%#= f.label :replydescription %>
      <%#= f.text_field :replydescription %>
      <%= label_tag 'Enter Reply ' %> <br/>
      <%= text_area_tag 'replydescription', @replydescription, rows: 3, cols: 25 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>




<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Back', :controller => "replies" , :action => "master" %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <tr>
    <th>Replydescription</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.replydescription %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/master.html.erb
<%= stylesheet_link_tag "posts" %>


<b>Post Title : </b>     </br> </br>
<%= @post.title  %> <br/>

</br> </br>

<b>Post Description : </b>     </br>  </br> </br>
<%= @post.postdescription  %> <br/>
 </br>

<% if @replies.any? %>
    <table>
      <tr>
        <th>Replied By</th>
        <th>Reply</th>
        <th>Vote Count</th>
      </tr>
      <% @replies.each do |reply| %>
          <tr>
            <% user = User.where(:id => reply.user_id) %>
            <% if user.count == 0 %>
                <td><%= "Anonymous" %></td>
            <% else %>
                <td><%= user[0].name %></td>
            <%end %>
            <td><%= reply.replydescription %></td>
            <td><%=  Replyvote.where(["replyvotes_id = :pid", { pid: reply.id}]).count %></td>
            <% user_id = reply.user_id%>
            <% if user_id.to_s == session[:userid].to_s %>
            <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
            <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else%>
            <% if !(session[:userid].to_s.nil? || session[:userid].to_s.empty?)   %>
            <% if Replyvote.where(["replyvotes_id = :pid and studentid = :sid", { pid: reply.id, sid: session[:studentid].to_s }]).count == 0 %>
                <td><%= link_to image_tag("like.jpg", :height =>40, :border=>0, :class => 'dock-item') , :controller => "replies", :action => "voteup", id: reply.id%></td>
            <% else %>
                <td><%= link_to image_tag("dislike.jpg", :height =>40, :border=>0, :class => 'dock-item') , :controller => "replies", :action => "votedown", id: reply.id%></td>
            <% end %>
                <% end %>
            <% end %>
          </tr>
      <% end %>
    </table>
<%end%>
<br>
<% if !(session[:username].to_s.nil? || session[:username].to_s.empty?) %>
<%= form_tag  do %>
    <%= label_tag 'Enter reply' %>
    <%= text_area_tag 'reply', nil, rows: 3, cols: 25 %>
    <%= submit_tag 'SaveReply' %>
<% end %>
<% end %>


app/views/replies/new.html.erb
<h1>New reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Replydescription:</b>
  <%= @reply.replydescription %>
</p>


<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>